###策略模式
person:
    maps: 
      DanJi: com.example.demo.handler.impl.DanJi
      WangLuo: com.example.demo.handler.impl.WangLuo
    name: zhangsan
    
spring:
####静态资源配置
  resources:
    static-locations: classpath:/static/,classpath:/public/
    
###freemarker配置
  freemarker:
    template-loader-path: classpath:/templates/
    charset: utf-8
    cache: false
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .html
    settings:
      template_update_delay: 1
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      number_format: #.##
      boolean_format: true,false

###json配置
  jackson:
    default-property-inclusion: always
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false


  datasource:
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sqlMapConfig.xml
  type-aliases-package: com.example.demo.domain



